erDiagram
    FUNCIONARIOS {
        NUMBER CODIGO_FUNCIONARIO PK "NOT NULL"
        VARCHAR2 NOME "NOT NULL"
        VARCHAR2 CPF "NOT NULL"
        VARCHAR2 CARGO "NOT NULL"
    }

    MARCACOES {
        NUMBER CODIGO_MARCACAO PK "NOT NULL"
        DATE DATA_MARCACAO "NOT NULL"
        DATE HORA_ENTRADA "NOT NULL"
        DATE HORA_SAIDA
        NUMBER CODIGO_FUNCIONARIO FK "NOT NULL"
    }

    FUNCIONARIOS ||--o{ MARCACOES : "possui"