erDiagram
    FUNCIONARIOS {
        NUMBER CODIGO_FUNCIONARIO PK
        VARCHAR2 NOME
        VARCHAR2 CPF
        VARCHAR2 CARGO
    }

    MARCACOES {
        NUMBER CODIGO_MARCACAO PK
        DATE DATA_MARCACAO
        DATE HORA_ENTRADA
        DATE HORA_SAIDA
        NUMBER CODIGO_FUNCIONARIO FK
    }

    FUNCIONARIOS ||--o{ MARCACOES : "possui"